name: HTML Check

on:
  push:
    branches:
    - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@v0.4.2
      with:
        root: .
        log_level: INFO
        css: true
    - uses: actions/upload-artifact@v2
      with:
        name: log
        path: log.log
